"""add statement_job table

Revision ID: 06a9bc8c453d
Revises: a210b74a5423
Create Date: 2026-09-06 00:17:35.289604

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06a9bc8c453d"
down_revision: str | Sequence[str] | None = "a210b74a5423"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statement_job",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("batch_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("intake_file_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("pdf_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "extraction_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'PROCESSING', 'RETRYING', 'COMPLETED', 'FAILED', 'UNSUPPORTED')",
            name="ck_statement_job_status",
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name="ck_statement_job_attempt_count_non_negative"
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["intake_file_id"],
            ["intake_file.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statement_job_batch_id"), "statement_job", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_statement_job_intake_file_id"),
        "statement_job",
        ["intake_file_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statement_job_intake_file_id"), table_name="statement_job")
    op.drop_index(op.f("ix_statement_job_batch_id"), table_name="statement_job")
    op.drop_table("statement_job")
    # ### end Alembic commands ###
